### ISSUE TITLE
Code for entity classification task

### ISSUE THREAD

**Issue by Maysir** [malllabiisc/CompGCN#2]
Hi,

Thanks for this amazing work! May I have your code for entity classification task?

**Comment by berlincho** [comment]
I am interested in the implementation of node classification, too.

**Comment by svjan5** [comment]
Sure, I will try to include that asap. Currently stuck with some work.

**Comment by CheriseZhu** [comment]
Hi, I can not reproduce the performance of the  proposed model on node classification task, and I'm not sure if the hyper-parameters are set incorrectly.
Can you show the hyper-parameter settings of node classification, including the number of  relation basis vectors, dropout rate, l2 penalty and other related detalis?

**Comment by lmhmhl** [comment]
Traceback (most recent call last):
  File "/home/ubantu/anaconda3/lib/python3.7/site-packages/torch_scatter/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/ubantu/anaconda3/lib/python3.7/site-packages/torch/_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "/home/ubantu/anaconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cpu.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from helper import *
  File "/media/ubantu/fb915eb5-f0ce-4b0a-8cc4-4e941d52b4b4/lmh/CompGCN-master(Modified)/helper.py", line 13, in <module>
    from torch_scatter import scatter_add
  File "/home/ubantu/anaconda3/lib/python3.7/site-packages/torch_scatter/__init__.py", line 21, in <module>
    raise OSError(e)
OSError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by BarclayII** [comment]
Any plan to include the node classification code?  Running on a single dataset is fine as well.

**Comment by svjan5** [comment]
An implementation of node classification experiments can be found here: 
https://github.com/zhjwy9343/dgl/pull/8
